### ISSUE TITLE
porrlyfill ? poorlyfill ?

### ISSUE THREAD

**Issue by k-j-kleist** [ungap/essential-map#2]
as in the repository description`?

as in README.md ?

**Comment by WebReflection** [comment]
as in where is the PR ?

**Comment by WebReflection** [comment]
Now I understand what is this about. **poorlyfill** is a word yes, it means a polyfill that is not standard compliant, so it provides a poor version of the standard, in this case only the basics, usually most needed, methods, not the whole package.

So, the essential part of ungap is about providing basic fallbacks that won't implement the whole polyfill for a reason or another, it's a poorlyfill.

Got it?
